### ISSUE TITLE
web module is not ESM syntax

### ISSUE THREAD

**Issue by ludamad** [noir-lang/noir-source-resolver#2]
### Aim

Trying to import in web-test-runner, gets issue that this is in node exports.foo syntax instead of export foo syntax
Also tsconfig.esm.json does not exist in the current repo

### Expected behavior

Web version should be ESM module

### Bug

Web version should be ESM module

### To reproduce

1.
2.
3.
4.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by jonybur** [comment]
Fixed by https://github.com/noir-lang/noir-source-resolver/pull/3
